dist: trusty
sudo: required

language: ruby
cache: bundler
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.6
  - 2.7.4

before_install:
  - gem install bundler -v 1.16.2

bundler_args: --without production

script:
  - bundle exec rspec spec

notifications:
  email: "snepote@gmail.com"

# safelist
branches:
  only:
  - master
